export const DEMO_ACCOUNTS = [
  {
    id: 'demo-participant',
    email: 'participant@codetowin.com',
    password: 'demo1234',
    role: 'participant',
    label: 'Participant',
    redirectTo: '/participant',
    profile: {
      firstName: 'Aminata',
      lastName: 'Diop',
      email: 'participant@codetowin.com',
      title: 'UI/UX & Product Designer',
      about: 'Designer produit passionnée par les interfaces utiles, accessibles et orientées impact.',
      bio: 'Je transforme des idées de hackathon en expériences claires et testables.',
      skills: 'Figma, Product Design, User Research, HTML/CSS',
      interests: 'Design, Hackathons, EdTech',
      city: 'Saint-Louis',
      country: 'Senegal',
      github: 'https://github.com/aminata-diop',
      linkedin: 'https://linkedin.com/in/aminatadiop',
      website: 'https://aminatadesign.com',
      visibility: 'public',
      isPublic: true,
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=160&h=160&q=80',
    },
  },
  {
    id: 'demo-mentor',
    email: 'mentor@codetowin.com',
    password: 'demo1234',
    role: 'mentor',
    label: 'Mentor',
    redirectTo: '/mentor',
    profile: {
      firstName: 'Ousmane',
      lastName: 'Diop',
      email: 'mentor@codetowin.com',
      title: 'Expert IA & Data Science',
      about: 'Mentor spécialisé dans le cadrage technique, la data science appliquée et la préparation des démos.',
      bio: 'J’aide les équipes à transformer des prototypes en solutions robustes.',
      skills: 'Python, Machine Learning, Data Science, Pitch',
      interests: 'IA, Climat, Mentorat',
      city: 'Dakar',
      country: 'Senegal',
      github: 'https://github.com/ousmane-diop',
      linkedin: 'https://linkedin.com/in/ousmanediop',
      website: 'https://ousmanediop.com',
      visibility: 'public',
      isPublic: true,
      avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=160&h=160&q=80',
    },
  },
  {
    id: 'demo-organizer',
    email: 'organizer@codetowin.com',
    password: 'demo1234',
    role: 'organizer',
    label: 'Organisateur',
    redirectTo: '/organizer',
    profile: {
      firstName: 'TechHub',
      lastName: 'Sénégal',
      email: 'organizer@codetowin.com',
      title: "Incubateur d'innovations numériques",
      about: "Organisation qui connecte talents tech, mentors et partenaires autour de hackathons africains.",
      bio: 'Nous organisons des challenges pour révéler les meilleurs builders.',
      skills: 'Innovation, Hackathons, Incubation, Data Science',
      interests: 'Startups, Talent Network, Impact',
      city: 'Dakar',
      country: 'Senegal',
      github: '',
      linkedin: 'https://linkedin.com/company/techhub-senegal',
      website: 'https://techhub.sn',
      visibility: 'public',
      isPublic: true,
      avatar: 'https://ui-avatars.com/api/?name=TechHub+Senegal&background=047857&color=fff',
    },
  },
  {
    id: 'demo-member',
    email: 'member@codetowin.com',
    password: 'demo1234',
    role: 'organizer',
    memberRole: 'Évaluateur',
    label: 'Membre organisateur',
    redirectTo: '/organizer/members',
    profile: {
      firstName: 'Nadia',
      lastName: 'Ba',
      email: 'member@codetowin.com',
      title: 'Évaluatrice projets',
      about: 'Membre invité dans un espace organisateur pour suivre les soumissions et aider à l’évaluation.',
      bio: 'J’analyse les projets, leur impact et la qualité de leur exécution.',
      skills: 'Évaluation, Produit, Impact, Pitch',
      interests: 'Innovation, Mentorat, Jurys',
      city: 'Abidjan',
      country: "Côte d'Ivoire",
      github: '',
      linkedin: 'https://linkedin.com/in/nadiaba',
      website: '',
      visibility: 'public',
      isPublic: true,
      avatar: 'https://ui-avatars.com/api/?name=Nadia+Ba&background=0f766e&color=fff',
    },
  },
];

export const getDemoAccount = (email = '') => (
  DEMO_ACCOUNTS.find((account) => account.email.toLowerCase() === String(email).trim().toLowerCase())
);

export const getRoleHome = (role = 'participant') => {
  if (role === 'organizer') return '/organizer';
  if (role === 'mentor') return '/mentor';
  return '/participant';
};
