export const initialHackathons = [
  {
    id: 'google-cloud-rapid-agent',
    title: 'CodeToWin Africa AI Sprint',
    start: '2026-06-01',
    end: '2026-06-12',
    deadline: '12 juin 2026',
    location: 'Accra, Ghana',
    type: 'Hybride',
    interest: 'Developers',
    prize: '$8,000',
    participants: 561,
    teams: 145,
    submissions: 120,
    online: true,
    status: 'publie',
    logoText: 'CT',
    keywords: 'codetowin africa ai sprint online hybrid devs makers ai'
  },
  {
    id: 'product-design-hack-weekend',
    title: 'Product Design Hack Weekend',
    start: '2026-06-10',
    end: '2026-06-14',
    deadline: '14 juin 2026',
    location: 'Lagos, Nigeria',
    type: 'En ligne',
    interest: 'Designers',
    prize: '$5,000',
    participants: 375,
    teams: 90,
    submissions: '-',
    online: true,
    status: 'publie',
    logoText: 'PD',
    keywords: 'product design hack weekend online remote designers founders builders ui ux'
  },
  {
    id: 'data-for-impact-challenge',
    title: 'Data for Impact Challenge',
    start: '2026-05-15',
    end: '2026-05-20',
    deadline: '20 mai 2026',
    location: 'Nairobi, Kenya',
    type: 'Présentiel',
    interest: 'Data Analysts',
    prize: '$6,000',
    participants: 214,
    teams: 54,
    submissions: 45,
    online: false,
    status: 'termine',
    logoText: 'DA',
    keywords: 'data for impact challenge in-person offline data analysts builders researchers social impact'
  },
  {
    id: 'young-innovators-lab',
    title: 'Young Innovators Lab',
    start: '2026-06-06',
    end: '2026-06-08',
    deadline: '8 juin 2026',
    location: 'Dakar, Senegal',
    type: 'En ligne',
    interest: 'Makers',
    prize: '$7,500',
    participants: 912,
    teams: 210,
    submissions: '-',
    online: true,
    status: 'attente',
    logoText: 'IN',
    keywords: 'young innovators lab online makers submissions developers designers students'
  },
  {
    id: 'cloud-security-open-hack',
    title: 'Cloud & Security Open Hack',
    start: '2026-06-18',
    end: '2026-06-22',
    deadline: '22 juin 2026',
    location: 'Kigali, Rwanda',
    type: 'Présentiel',
    interest: 'Security',
    prize: '$9,000',
    participants: 184,
    teams: 40,
    submissions: '-',
    online: false,
    status: 'brouillon',
    logoText: 'CS',
    keywords: 'cloud and security open hack in-person offline builders devs makers engineers security cloud'
  }
];
