# Generated by Django 6.0.6 on 2026-06-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0002_hackathonannouncement_hackathonregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='hackathon_banners/'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='faqs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='hackathon_logos/'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='max_team_size',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='min_team_size',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='registration_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='registration_mode',
            field=models.CharField(default='open', max_length=50),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='registration_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='resources',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='rules',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='technologies',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
