# Generated by Django 6.0.6 on 2026-06-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0003_hackathon_banner_hackathon_faqs_hackathon_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='participant_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
