# Generated by Django 6.0.6 on 2026-06-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0004_hackathon_participant_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='registration_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='registration_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
