# Generated by Django 6.0.6 on 2026-06-21 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0005_alter_hackathon_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('Soumis', 'Soumis'), ('Évalué', 'Évalué')], default='Soumis', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_teams', to='hackathons.hackathonmentor'),
        ),
    ]
