# Generated by Django 6.0.6 on 2026-06-22 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0007_hackathon_results_published_submission_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='jury_questions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='submission',
            name='jury_answers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
