# Generated by Django 6.0.6 on 2026-06-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0009_hackathondiscussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='invite_token',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
