# Generated by Django 6.0.6 on 2026-07-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0010_team_invite_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_solo',
            field=models.BooleanField(default=False),
        ),
    ]
