# Generated by Django 6.0.6 on 2026-06-22 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0007_hackathon_results_published_submission_feedback_and_more'),
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('declined', 'Refusée')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_invitations', to='hackathons.hackathon')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='mentor.mentorprofile')),
            ],
            options={
                'unique_together': {('hackathon', 'mentor')},
            },
        ),
    ]
