# Generated by Django 6.0.6 on 2026-06-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerprofile',
            name='linkedin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organizer_logos/'),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='twitter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
